# Use container-based environment (faster startup, allows caches).
sudo: false
language: python
python:
  - "3.4"
env:
  - TESTENV=pypy-master-sqlite_file
  - TESTENV=pypy3-master-sqlite_file
  - TESTENV=python2.6-1.6-sqlite_file
  - TESTENV=python2.7-1.3-sqlite_file
  - TESTENV=python2.7-1.4-sqlite_file
  - TESTENV=python2.7-master-mysql_innodb
  - TESTENV=python2.7-master-mysql_myisam
  - TESTENV=python2.7-master-sqlite_file
  - TESTENV=python3.2-master-sqlite_file
  - TESTENV=python3.3-master-sqlite_file
  - TESTENV=python3.4-1.5-sqlite_file
  - TESTENV=python3.4-1.6-sqlite_file
  - TESTENV=python3.4-1.7-sqlite_file
  - TESTENV=python3.4-1.8-sqlite_file
  - TESTENV=python3.4-master-postgres
  - TESTENV=python3.4-master-sqlite
  - TESTENV=python3.4-master-sqlite_file
  - TESTENV=checkqa-python2.6
  - TESTENV=checkqa-python2.7
  - TESTENV=checkqa-python3.2
  - TESTENV=checkqa-python3.3
  - TESTENV=checkqa-python3.4
  - TESTENV=checkqa-pypy
  - TESTENV=checkqa-pypy3
matrix:
  allow_failures:
    - env: TESTENV=pypy-master-sqlite_file
    - env: TESTENV=pypy3-master-sqlite_file
    - env: TESTENV=python2.7-master-mysql_innodb
    - env: TESTENV=python2.7-master-mysql_myisam
    - env: TESTENV=python2.7-master-sqlite_file
    - env: TESTENV=python3.2-master-sqlite_file
    - env: TESTENV=python3.3-master-sqlite_file
    - env: TESTENV=python3.4-master-postgres
    - env: TESTENV=python3.4-master-sqlite
    - env: TESTENV=python3.4-master-sqlite_file
install:
  - travis_retry pip install tox
script: travis_retry tox -e $TESTENV