language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
env:
  - DJANGO_VERSION=1.3.1
  - DJANGO_VERSION=1.4
install:
  - pip install --use-mirrors -q pytest
  - pip install --use-mirrors -q django==$DJANGO_VERSION
  - python setup.py develop
script: DJANGO_SETTINGS_MODULE=tests.settings py.test
